require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'PGPChatApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'


  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'


  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'

  pod 'react-native-image-keyboard', :path => '../node_modules/react-native-image-keyboard'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  target 'PGPChatAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'PGPChatApp-tvOS' do
  # Pods for PGPChatApp-tvOS

  target 'PGPChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
