name: Build and Deploy PGPChatAppLandingPage

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'PGPChatAppLandingPage/**'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: 'yarn'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node modules
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('PGPChatAppLandingPage/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn install
        working-directory: ./PGPChatAppLandingPage
        run: yarn install
      - name: Build
        working-directory: ./PGPChatAppLandingPage
        run: yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./PGPChatAppLandingPage/dist
